### ISSUE TITLE
CI to check that cts.json has been built

### ISSUE THREAD

**Issue by glyn** [jsonpath-standard/jsonpath-compliance-test-suite#33] opened 2023-04-20 01:29 UTC
To avoid the situation where cts.json gets out of step with the built version, we could define a CI check that builds cts.json and makes sure it equals the version checked in.

**Comment by f3ath** [comment] 2023-04-20 02:12
I think we can just build and commit it as a CI step. I see no reason to ask contributors to build it manually.

**Comment by glyn** [comment] 2023-04-20 02:22
That would work, but JSONPath implementers might want to ensure that their implementation passes with the updated cts.json _before_ submitting a PR to the CTS. For instance, they could modify a git submodule containing the CTS, get everthing passing, and then push the CTS change. So they'd actually prefer to build cts.json rather than have a more complicated workflow of submitting a PR in order to consume the built cts.json.

**Comment by gregsdennis** [comment] 2023-04-20 03:08
No, I agree with @f3ath.  If the CI step doesn't successfully build and commit the CTS, then the PR doesn't get merged.  It's up to the submitter to ensure its working. If that means they build locally, okay, but they shouldn't have to.

**Comment by glyn** [comment] 2023-04-20 06:37
I think the effect would be the same: the result of a PR would be a built cts.json that corresponds to the constituent input files. The benefit of my proposed approach is that it requires the developer to build cts.json and so it encourages the workflow I described. But I can live with CI building and committing cts.json if that's the consensus.

**Comment by gregsdennis** [comment] 2023-04-20 06:41
> it requires the developer...

This is not a benefit. Developers generally prefer _not_ to do things that automation can do for them.

**Comment by glyn** [comment] 2023-04-20 06:50
Just think about the workflow if I want to get my implementation passing the updated CTS before I submit a PR. How will CI automation help me?

**Comment by gregsdennis** [comment] 2023-04-20 07:07
There's nothing stopping you from running it locally anyway. This is an assist for developers that don't want to or or aren't set up to run it locally.

**Comment by glyn** [comment] 2023-04-20 07:11
Ok, I understand the counter-argument and am happy to go with the consensus.

**Comment by Marcono1234** [comment] 2024-02-25 16:58
Regarding the workflow verifying that `cts.json` is up-to-date, I have implemented that in https://github.com/Marcono1234/jsonpath-compliance-test-suite/tree/cts-check-workflow before noticing the discussion here...
If you are interested in it nonetheless, please let me know.

Regarding updating `cts.json` automatically: The question would then be whether to do that only on pushes to the `main` branch, or also / instead try to update the pull requests themselves. But I am not sure if that is easily possible and might interfere with the actions of the submitter if they want to push additional commits.
In general that could probably be implemented with actions similar to https://github.com/stefanzweifel/git-auto-commit-action; however for all these actions there is the limitation that these push events caused by workflows [will not trigger any other workflows](https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#commits-made-by-this-action-do-not-trigger-new-workflow-runs). Not sure if that will be an issue here though.

**Comment by gregsdennis** [comment] 2024-02-25 21:25
I'm happy for it to only occur on pushes to `main`.  I don't think that will interfere with people doing it themselves and including the recompilation in a PR.

I don't think that we need to worry about triggering from other workflows; just the push to main should suffice.

If you'd like to make a PR, I'm happy to take a look.

**Comment by Marcono1234** [comment] 2024-02-25 22:21
> If you'd like to make a PR, I'm happy to take a look.

I was currently creating a similar workflow for a different project:
https://github.com/gradle/wrapper-validation-action/pull/187/files#diff-fff36062a553629972ffa0fe5201fa6901e257632b9cca0bc690d6433ce941ec

Do you think something similar to this (with corresponding adjustments for this project here) would be fine?

Assuming that the `main` branch is protected, it might need [additional configuration](https://github.com/stefanzweifel/git-auto-commit-action/tree/master?tab=readme-ov-file#push-to-protected-branches), but I am not completely sure.

**Comment by gregsdennis** [comment] 2024-02-25 22:36
Yeah, that's basically how I would expect this to work.  I like the change verification step, too.

(`main` isn't protected right now, but I can't say it'll stay that way.)

**Closed** 2024-03-02 00:27 UTC
